name: "Setup api"
description: "Checkout project and install dependencies"
runs:
  using: "composite"
  steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Cache Go modules
      uses: actions/cache@preview
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: go get -v -t -d ./...
      shell: bash
